/** One-line page descriptions. Components not listed fall back to the registry description. */
export const descriptions: Record<string, string> = {
  accordion: "A vertically stacked set of interactive headings that each reveal a section of content.",
  "alert-dialog": "A modal dialog that interrupts the user with important content and expects a response.",
  alert: "Displays a callout for user attention.",
  avatar: "An image element with a fallback for representing the user.",
  badge: "Displays a badge or a component that looks like a badge.",
  breadcrumb: "Displays the path to the current resource using a hierarchy of links.",
  button: "Displays a button or a component that looks like a button.",
  "button-group": "Groups related buttons into a single control.",
  calendar: "A date field component that allows users to enter and edit dates.",
  card: "Displays a card with header, content, and footer.",
  carousel: "A carousel with motion and swipe built on Embla.",
  cascader: "Drill through columns of options; the answer reads as a path.",
  chart: "Recharts wrapped in themed containers, tooltips, and legends.",
  chat: "A compositional chat layout: conversation list, thread, and composer.",
  checkbox: "A control that allows the user to toggle between checked and not checked.",
  collapsible: "An interactive component which expands or collapses a panel.",
  combobox: "Autocomplete input and command palette with a list of suggestions.",
  command: "Fast, composable command menu on Ark UI's Listbox.",
  "context-menu": "Displays a menu at the pointer, triggered by a right click.",
  "data-grid": "An editable, keyboard-driven grid with ranges, copy and paste, and per-type editors.",
  "data-table":
    "Compositional table parts on a dependency-free headless engine: sorting, filters, pagination, selection.",
  dialog: "A window overlaid on the primary window, rendering the content underneath inert.",
  drawer: "A panel that slides in from the edge of the screen, with stacking.",
  "dropdown-menu": "Displays a menu to the user, triggered by a button.",
  field: "Label, description, and error parts for form controls.",
  gantt: "A timeline with draggable bars, milestones, dependency arrows, and zoom.",
  "hover-card": "For sighted users to preview content available behind a link.",
  hotkeys: "A keyboard shortcut registry with chords, sequences, and a cheat-sheet dialog.",
  input: "Displays a form input field or a component that looks like an input field.",
  "input-group": "Inputs with leading and trailing addons, text, and triggers.",
  "input-otp": "Accessible one-time-password input with copy-paste functionality.",
  kanban: "A data-agnostic board with drag-and-drop and keyboard card and column moves.",
  kbd: "Displays keyboard keys.",
  label: "Renders an accessible label associated with controls.",
  "live-region": "A screen-reader announcer for actions that have no visible feedback.",
  menubar: "A horizontal menu bar, common in desktop applications.",
  "navigation-menu": "A collection of links for navigating websites.",
  "node-graph": "A visual-scripting node editor: pan, zoom, ports, edges, selection, and context menus.",
  pagination: "Pagination with page navigation, next and previous links.",
  popconfirm: "An inline confirmation on a popover, no modal.",
  popover: "Displays rich content in a portal, triggered by a button.",
  progress: "Displays an indicator showing the completion progress of a task.",
  "query-builder": "A filter builder that reads like a sentence.",
  "radio-group": "A set of checkable buttons where no more than one can be checked at a time.",
  resizable: "Accessible resizable panel groups and layouts with keyboard support.",
  "rich-text-editor": "A compositional editor on tiptap with toolbar, bubble menu, and character count.",
  scheduler: "A calendar with day, week, and month views, drag to move, resize, and create.",
  "scroll-area": "Augments native scroll functionality for custom, cross-browser styling.",
  select: "Displays a list of options for the user to pick from, triggered by a button.",
  separator: "Visually or semantically separates content.",
  sheet: "Extends the Dialog component to display content that complements the main content of the screen.",
  sidebar: "A composable, themeable and customizable sidebar component.",
  skeleton: "Use to show a placeholder while content is loading.",
  slider: "An input where the user selects a value from within a given range.",
  sonner: "An opinionated toast component for React.",
  switch: "A control that allows the user to toggle between on and off.",
  table: "A responsive table component.",
  tabs: "A set of layered sections of content, known as tab panels, displayed one at a time.",
  textarea: "Displays a form textarea or a component that looks like a textarea.",
  toggle: "A two-state button that can be either on or off.",
  "toggle-group": "A set of two-state buttons that can be toggled on or off.",
  tooltip: "A popup that displays information related to an element when it receives focus or hover.",
  "transfer-list": "Move items between two lists with search, select all, and keyboard support.",
  "tree-select": "Pick one node from a hierarchy, or many with branch checkboxes.",
  "tree-view": "A hierarchical list with expand, collapse, selection, and checkboxes.",
  "virtual-list": "Render only the rows in view, whatever the row count.",
  "angle-slider": "Pick an angle by dragging around a dial.",
  attachment: "A file attachment row with media, name, size, upload state, and actions.",
  bubble: "Chat bubbles with alignment, variants, and reactions.",
  clipboard: "An input with a copy button that confirms the copy.",
  "color-picker": "Pick a color with an area, channel sliders, swatches, and an eye dropper.",
  "date-input": "A segmented date field: month, day, and year typed in place.",
  direction: "Provide a text direction (LTR or RTL) to every component below it.",
  editable: "Text that turns into an input when clicked, with submit and cancel.",
  empty: "An empty state with media, title, description, and actions.",
  "file-upload": "A drop zone and file list with previews, sizes, and delete triggers.",
  "floating-panel": "A draggable, resizable panel that can minimize and maximize.",
  "image-cropper": "Crop an image with a draggable selection, grid, and handles.",
  item: "A list row with media, content, and actions.",
  "json-tree-view": "Browse any JSON value as an expandable tree with typed values.",
  marker: "A map-style pin with an icon and a label.",
  marquee: "Content that scrolls continuously, with fades at the edges.",
  message: "A chat message with avatar, header, content, and footer.",
  "number-input": "A numeric field with increment and decrement triggers and a scrubber.",
  "password-input": "A password field with a visibility toggle.",
  "qr-code": "Render a QR code for any value, with an optional overlay.",
  "rating-group": "Star ratings, with half steps and keyboard support.",
  "segment-group": "A segmented control for switching between a few views.",
  "signature-pad": "Draw a signature; get it back as an image.",
  spinner: "An indeterminate loading indicator.",
  steps: "A multi-step flow with a progress list and per-step content.",
  swap: "Swap between two elements, for icon toggles.",
  "tags-input": "Type values into a list of removable tags.",
  timer: "A count-up or countdown timer with start, pause, and reset.",
  toc: "A table of contents that tracks the heading in view.",
  tour: "Guided product tours with spotlights, tooltips, and steps.",
  "activity-feed": "A timeline of events with groups, markers, actors, and relative times.",
  "app-shell": "The application frame: collapsible sidebar, header with search and notifications, and main area.",
  "aspect-ratio": "Displays content within a desired ratio.",
  canvas: "A drag-and-drop layout surface for rows and columns of nodes.",
  "comment-thread": "Comments with replies, reactions, editing, and an @mention composer.",
  "floating-toolbar": "A floating action bar for pending selections and unsaved changes.",
  format: "Locale-aware number, byte, and relative time formatting.",
}
