import { readFileSync } from "node:fs"
import { join } from "node:path"

/** The registry shipped inside this package (generated by scripts/build-registry.mjs). */
export const bundledDir = new URL("../registry/", import.meta.url).pathname

/**
 * A registry source: the bundled directory by default, or a base URL (`--registry`,
 * `ARKCN_REGISTRY`) such as https://raw.githubusercontent.com/itsdanreed/arkcn/main/registry
 */
export function createRegistry(base) {
  const remote = base && /^https?:\/\//.test(base)
  const read = async (rel) => {
    if (!remote) return readFileSync(join(base ?? bundledDir, rel), "utf8")
    const url = `${base.replace(/\/$/, "")}/${rel}`
    const res = await fetch(url)
    if (!res.ok) throw new Error(`Registry request failed: ${res.status} ${url}`)
    return res.text()
  }
  const cache = new Map()
  const cached = (rel, parse) => {
    if (!cache.has(rel)) cache.set(rel, read(rel).then(parse))
    return cache.get(rel)
  }
  return {
    source: remote ? base : "bundled",
    index: () => cached("index.json", JSON.parse),
    item: (name) => cached(`items/${name}.json`, JSON.parse).catch(() => null),
    baseCss: () => cached("base.css", (s) => s),
    /** Every item needed to install `names`, dependencies first, each once. */
    async closure(names) {
      const ordered = []
      const seen = new Set()
      const missing = []
      const visit = async (name, chain) => {
        if (seen.has(name)) return
        const item = await this.item(name)
        if (!item) {
          missing.push(chain.length ? `${name} (needed by ${chain[chain.length - 1]})` : name)
          return
        }
        seen.add(name)
        for (const dep of item.registryDependencies) await visit(dep, [...chain, name])
        ordered.push(item)
      }
      for (const name of names) await visit(name, [])
      return { items: ordered, missing }
    },
  }
}
